name: first
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Welcome message
          run: echo "welcome to github actions"
        - name: checkout code
          uses: actions/checkout@v4    

